### ISSUE TITLE
[BUG] MacOS: Multitouch introduction causes issues (Flutter 3.3.0)

### ISSUE THREAD

**Issue by JosefWN** [fleaflet/flutter_map#1354]
### What is the bug?

With Flutter's new multitouch support [extending to desktop](https://github.com/flutter/flutter/issues/23604), the default behavior in `flutter_map` on Flutter 3.3.0 is two finger pan/rotate and pinch to zoom. This is completely in line with the Apple Maps app on Mac for example.

A couple of issues:
- [x] When I rotate clockwise with my fingers, the map rotates counter-clockwise. EDIT: Fixed in Flutter engine in a coming release.
- [x] ~The panning threshold is a bit tight, so you need some speed when you two-finger swipe to get it to continue the panning as an animation. With slight movements there is no animation and the pan stops abruptly, which is not the case in the native Maps application on macOS for example.~
- [ ] Pinch to zoom does not center zoom on mouse pointer.
- [x] Pinch to rotate does not center rotation on mouse pointer.

It seems like https://github.com/fleaflet/flutter_map/issues/1358 is also related to this umbrella issue (where a `resolutions` list is provided, there seems to be bound checks for other gestures like scroll to zoom, but not for pinch to zoom). Tracked in a separate ticket.
 
Combined rotation and zoom in a single gesture (which works just fine on iPad) doesn't seem to work on Mac at all, neither with `flutter_map` nor Apple Maps, unless it's some setting I need to change on my end. Tried disabling some more complex multitouch gestures in the macOS settings to see if they could be interfering but that was not the case.

As things stand right now I almost liked the old behavior (with scroll to zoom and click & drag to pan) a bit more, although that prevented me from rotating the map intuitively.

### What is the expected behaviour?

Rotating clockwise with a touch gesture in Apple Maps or rotating images in Preview (macOS) rotates the canvas clockwise. The same goes for `flutter_map` built for iPad. It would make sense if it worked the same way on macOS.

### How can we reproduce this issue?

Run on macOS with a touchpad, try to rotate the canvas with a touch gesture.

### Can you provide any other information?

Running `flutter_map` 3.0.0-beta3 on M1 Macbook Air.

### Platforms Affected

MacOS

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

---

EDIT by @JaffaKetchup: The second bullet point above is a low priority enhancement unrelated to the main issue, so that will be ignored for now. Please create a separate feature request for this, if still wanted.

**Comment by JaffaKetchup** [comment]
Hi @JosefWN,
I can't verify this as I don't have a Mac: can you post a screen recording?
In terms of the new image provider mechanisms, I've just seen that after updating. We'll be releasing v3 with 4 counts of deprecated APIs, as we may be rewriting quite a bit of the surrounding code anyways. If you can help migrate to the new APIs, that would be greatly appriciated!
Many thanks!

**Comment by JaffaKetchup** [comment]
Just added Flutter 3.3.0 support (in terms of the `DecoderBufferCallback` and `loadBuffer` inside the image providers) in #1355. Hopefully this doesn't break support for <3.3.0!

**Comment by TesteurManiak** [comment]
I've tested the gestures with the sample application on my MacBook M1 Pro:
- Didn't have any issue with the combined rotation & zoom (can send a video for proof), as you said it might be an issue on your end.
- Still cannot reproduce the exception you've mentionned in #1358 

I'm going to take a look at the clockwise rotation, I think you might already be able to customize the behavior with the provided properties but I guess it would be nice to have it implemented by default on MacOS.

For the pinch to zoom on the mouse pointer I wonder if this behavior should be specific to MacOS or generalized to all desktop platforms (maybe web too).

**Comment by JosefWN** [comment]
> Didn't have any issue with the combined rotation & zoom (can send a video for proof), as you said it might be an issue on your end.

I didn't know that was possible on macOS? I've never been able to do it in _any_ program on my Macbook Air M1, that is, in a single touch gesture (not two gestures), both zoom and rotate similarly to what you can do on iOS. New feature on the Macbook Pro's or some hidden setting somewhere? Yeah can you please send the video, I'm curious if we are talking about the same thing. I will dig out my old Macbook Pro as well just to see if something is wrong with my Macbook Air.

> I'm going to take a look at the clockwise rotation, I think you might already be able to customize the behavior with the provided properties but I guess it would be nice to have it implemented by default on MacOS.

In my case I target macOS, Linux, Windows, iOS and Android... can become a lot of code duplicated over every library user's code base.

I will try to make videos as well, showing the difference between how the same app acts on iPad (everything touch-related works since pre-Flutter 3.3.0) and macOS (multiple issues since Flutter 3.3.0). I could try re-installing Flutter before that, just for the heck of it, to make sure it's not my own install that's borked.

**Comment by JosefWN** [comment]
> I will dig out my old Macbook Pro as well just to see if something is wrong with my Macbook Air.

Same on Macbook Pro 2017, just tried rotating and zooming in a combined gesture ("pinch and rotate") on a picture in Preview and it starts flickering, competing for either zoom or rotate. Could be good to be aware of this limitation on the touchpads if you've come to expect the functionality from iOS to carry over to macOS. Perhaps it's only the latest high-end laptops that support this, then.

**Comment by TesteurManiak** [comment]
Here's the video:
https://user-images.githubusercontent.com/14369698/189156750-8d4abb4e-60f6-46b3-80f3-ebaf2bf0cde4.mp4

**Comment by JosefWN** [comment]
> Here's the video:
https://user-images.githubusercontent.com/14369698/189156750-8d4abb4e-60f6-46b3-80f3-ebaf2bf0cde4.mp4

Not sure we are talking about the same thing, I can't clearly see the combined gesture in your video.

This is what I'm talking about (example on iOS where it works):
https://user-images.githubusercontent.com/12534742/189218486-9892f53e-82c8-42db-af48-6c3350feb4b5.mov

But as I said, I think this is a touchpad limitation rather than an issue with Flutter. No other app seems to support this behavior on macOS either. Tested with Preview and Affinity Designer and neither seem to support "pinch and rotate" to both zoom and rotate at the same time.

> Still cannot reproduce the exception you've mentionned in https://github.com/fleaflet/flutter_map/issues/1358

Clarified the ticket with steps to reproduce and a screenshot. Running a fresh install of Flutter 3.3.0 and an untouched `flutter_map` (master).

**Comment by JosefWN** [comment]
Example in this video:
- Clockwise rotation (showing as counterclockwise on the map)
- Pinch to zoom, mouse in the upper right corner of the window as I'm zooming in, and upper left corner as I'm zooming out, but `flutter_map` seems to use the center of the window.

https://user-images.githubusercontent.com/12534742/189221949-22378827-1479-42aa-8c4b-a74219a750ed.mp4

**Comment by ibrierley** [comment]
Out of interest, does it all work correct in Google Maps ?

**Comment by TesteurManiak** [comment]
> Out of interest, does it all work correct in Google Maps ?

I've tested Google Maps on MacOS with Google Chrome and the pinch to zoom is influenced by the mouse position.

**Comment by JosefWN** [comment]
> Out of interest, does it all work correct in Google Maps ?

> I've tested Google Maps on MacOS with Google Chrome and the pinch to zoom is influenced by the mouse position.
And the map is rotated clockwise.

Pinch works for me but I've never gotten rotation touch gestures to work in the browser. On macOS `flutter_map` pre-Flutter 3.3.0 I used to use the scroll, there was a PR fixing support for zooming on cursor position when scrolling: https://github.com/fleaflet/flutter_map/pull/1191

The touchpad works correctly on Apple Maps (the macOS app), I haven't noticed any issues with `flutter_map` on iOS either. Couldn't find Google Maps or anything but an ancient Google Earth Pro for installation on macOS to try the native experience.

**Comment by JosefWN** [comment]
I have tested a bit more throughly and updated the list in my initial post.

I have also looked around online and found that although there is a JavaScript touch API [supporting multitouch](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Multi-touch_interaction), it seems that more complex gestures have scarce support on the web, especially the twist gesture for rotations. Support also seems to be lacking in [Safari](https://caniuse.com/touch), so multitouch in the browser on iPad for example is also limited (it seems pinch to zoom works in the browser but not pinch to rotate).

For testing we might need to use native applications like Apple Maps on macOS, if we want to align with the native multitouch behavior and leverage multitouch fully, as opposed to comparing to Google Maps. Hopefully this is somewhat cross-platform too, so we only need one implementation to support multitouch trackpads on laptops.

The touch issues are not major, but enough to be quite annoying to the user experience. If I manage I'll have a look at the touch code, but I have no experience working with touch, so I'd be happy if someone else beat me to it 😅

**Comment by ianthetechie** [comment]
Just came here to confirm that the pinch rotate (and to a much lesser extent zoom as well) behavior feels pretty unnatural on Mac. If anyone can point me to the relevant code, I'd be happy to take a look. I'm actually a bit new to Flutter dev, but have over 10 years of experience building macOS and iOS apps so I'd be happy to be a sounding board and contribute code or otherwise.

**Comment by JaffaKetchup** [comment]
Hi @ianthetechie. I can't point you to the code right now, but all help is appreciated! If you go into the `FlutterMap` state, I think there's a gesture arena inside, and it's quite a complicated bit of code.

**Comment by ianthetechie** [comment]
@JaffaKetchup I fired up a good ol debug session and have a vague idea of what's up now... It looks like you're essentially using the Flutter stdlib scale gesture recognizer (small miracle this exists in essentially pure dart... that's on MASSIVE hunk of code!) and just taking the gesture rotation value from the events it generates, so this actually might be an upstream issue. I have a feeling nobody at Google cares about Mac or something. I'll go poke around there a bit more and maybe raise an issue upstream, but an hour or 2 of poking seems to indicate it might not be your problem.

**Comment by JaffaKetchup** [comment]
Bug thanks @ianthetechie :). Yeah, I'm not familiar with the gesture code, and you seem to be much more comfortable with it.

I know we use positioned_tap_detector (maybe v2), maybe that's part of the problem? Not sure to be honest. But if you found for rotation that we're just using values from somewhere else and not modifying them in any way, that would certainly indicate an issue on their part.
I guess part of the problem is, we have a very niche set of gesture detections and rules, so nobody probably realised before - if it is indeed their issue.

**Comment by ianthetechie** [comment]
No worries. I've come up with an [MRE](https://github.com/ianthetechie/flutter_macos_scale_mre) demonstrating the issue using nothing but a super vanilla Flutter app and standard components, so the positioned tap detector isn't likely an issue here.

I opened a discussion on the Flutter official discord. Unless someone tells me I'm stupid / "holding it wrong" I'll update you guys here once it's tracked there via a GitHub issue ;)

**Comment by ianthetechie** [comment]
Acknowledged by a Flutter dev, who just opened a PR: https://github.com/flutter/engine/pull/36444. What a quick turnaround :D

**Comment by JaffaKetchup** [comment]
Hooray! Indeed a quick turnaround :)

**Comment by brentlintner** [comment]
Side note here:

We ran into this regression ourselves (lack of momentum). To get the previous behaviour back (for anyone reading this) just revert flutter_map to v.2.2.0 and Flutter v3.0.5, which seems to work.

Thanks for looking into this btw!! 👏 ❤️

**Comment by JaffaKetchup** [comment]
Ok, the https://github.com/flutter/engine/pull/36444 PR seems to have been merged, so it is either already available, or will be available soon. It seems like this is the root cause (please correct me if I am misunderstanding), so I will close this issue for now. Please ping me if you need it reopened!

**Comment by ianthetechie** [comment]
IMO there are still some follow-up tasks here. The upstream issue that was fixed (looks slated for release in 3.4) just fixes the problem with polarity being wrong, which was huge 😂 The "unnatural-ness" described (points 2-4) are still open bugs and I haven't yet had time to determine if they are issues with `flutter_map` or upstream. I would suspect several of them are in this codebase though so I'm not sure we can close the issue yet.

Once the upstream fix drops in stable, think (someone who knows the ecosystem better correct if I'm wrong) the resolution from the `flutter_map` side will be to depend on Flutter 3.4.0 (or whatever), no? Coming from Apple dev land or Rust, it's pretty reasonable to only support the latest SDK as a bulid target but idk if that's the norm here.

**Comment by JaffaKetchup** [comment]
Hi @ianthetechie, in this case I will reopen.

In terms of depending on the latest Flutter SDK, it should be ok? That is quite confusing in Flutter, as you've got the local Flutter versions that your machine can actually run, then every project has its own version bounds, but sometimes those are ignored. It should be ok, as 3.4 will be non breaking.

**Comment by JosefWN** [comment]
Can we disable the stale bot perhaps? Seems like more trouble than help...

**Comment by JaffaKetchup** [comment]
@JosefWN We can I think, but it helps to keep me on top of things when waiting for responses etc.

**Comment by JaffaKetchup** [comment]
It would probably be better to add an exception tag so the bot skips certain issues. I'll think about implementing that.

**Comment by JaffaKetchup** [comment]
@JosefWN I think the bottom two points are now fixed in 'master' for v4. Please confirm.

In terms of the remaining point, I think that's more of an enhancement/feature addition than a bug. The 'animation' is known as the fling - and you're right that there is probably a threshold somewhere. But I think this is really low priority.

If you can confirm that the bottom two points are resolved, I'll close this issue.

**Comment by JosefWN** [comment]
> Pinch to zoom does not center zoom on mouse pointer.

This is still an issue I think, but the other point you mention seems to be solved!

**Comment by JaffaKetchup** [comment]
Hey @JosefWN,
When you get a moment, can you re-evaluate whether this issue is still applicable in the 'master' branch with the latest Flutter 3.10 version?
Thanks!

**Comment by JosefWN** [comment]
Hi, yes, this is still valid on latest Flutter/Dart/flutter_map/macOS. My guess is that we need to do something analogous to what we did for rotations? https://github.com/fleaflet/flutter_map/pull/1437
