### ISSUE TITLE
'tile.openstreetmap.org' Inaccessible On Web (due to CORS-POLICY)

### ISSUE THREAD

**Issue by RomanIvn** [fleaflet/flutter_map#1489]
### What is the bug?

I have several application that have been deployed on the web & also developing local host web apps with this setup:

```dart
 Widget map = LayoutBuilder(
            builder: (ctx, constraints) {
              return Center(
                  child: FlutterMap(
                options: MapOptions(
                  center: LatLng(32.8, 35.0),
                  zoom: 10.5,
                  minZoom: 10.5,
                  maxZoom: 18,
                  interactiveFlags: InteractiveFlag.pinchZoom | InteractiveFlag.drag,
                ),
                children: [
                  TileLayer(
                    urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                    userAgentPackageName: 'com.test.app',
                  ),
                  MarkerClusterLayerWidget(
                    options: MarkerClusterLayerOptions(
                      //spiderfyCluster: false,
                      //disableClusteringAtZoom: 16,
                      showPolygon: false,
                      maxClusterRadius: 40,
                      size: const Size(30, 30),
                      anchor: AnchorPos.align(AnchorAlign.center),
                      fitBoundsOptions: const FitBoundsOptions(
                        padding: EdgeInsets.all(40),
                        maxZoom: 18,
                      ),
                      markers: [],
                      /*projects.where((p) => p['location'] != null).map<Marker>((project) {
                            return Marker(
                              point: LatLng(project['location']['lat'], project['location']['lon']),
                              width: 40,
                              height: 40,
                              builder: (context) => Column(mainAxisAlignment: MainAxisAlignment.start, children: [
                                IconButton(
                                  icon: Icon(Icons.location_on, color: Colors.orange),
                                  onPressed: () {
                                  },
                                )
                              ]),
                            );
                          }).toList()*/
                      builder: (context, markers) {
                        return Container(
                          decoration: BoxDecoration(borderRadius: BorderRadius.circular(20), color: Colors.orange),
                          child: Center(
                            child: Text(
                              markers.length.toString(),
                              style: const TextStyle(color: Colors.white),
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ],
              ));
            },
          );
```

Suddenly all of them stopped showing tiles due to CORS-POLICY:
```Access to XMLHttpRequest at 'https://tile.openstreetmap.org/11/1227/826.png' from origin 'http://localhost:7244' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

### What is the expected behaviour?

I except the map tiles to keep showing as they used to as I haven't done any changes in the production apps to break anything.

### Platforms Affected

Web

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates

**Comment by ibrierley** [comment]
It looks a bit like something has changed a the Openstreetmap server, not sure if this is permanent, or a temporary glitch (I don't think it was there yesterday).

You could try adding a header like   "Access-Control-Allow-Origin": "*"

Example, maybe at https://github.com/fleaflet/flutter_map/issues/1458  let us know how you get on, as I suspect this may become a major issue.

**Comment by RomanIvn** [comment]
Changed to:
```
                  TileLayer(
                    urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    subdomains: const ['a', 'b', 'c'],
                    userAgentPackageName: "app.roman.com",
                    tileProvider: NetworkNoRetryTileProvider(
                      headers: {
                        "Access-Control-Allow-Origin": "*",
                      },
                    ),
                  ),
```
And PC&Android chrome still do not work.

I have tested through Safari on PC, Opera&Chrome on iOS  and the **do work**.
Looks like a specific issue with Chrome on Android&Windows

**Comment by JaffaKetchup** [comment]
Not sure why it might make a difference, but try omitting the subdomain. Everything appears to be working on my Android (app).

**Comment by RomanIvn** [comment]
Definately something with Open

> ```dart
> https://tile.openstreetmap.org/{z}/{x}/{y}.png
> ```

have you tried this sever:
'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
On Web (Android+Windows)?

Also, I've switched to this server:
https://a.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png

and it works...

**Comment by ozkayas** [comment]
I have been facing a similar problem since this morning. I am unsure if it is related but I upgraded Flutter to 3.7.11 yesterday.

```
return TileLayer(
                      urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png,
                      subdomains: const ['a', 'b', 'c'],
                    );
```

Error:
```
======== Exception caught by image resource service ================================================
The following ClientException was thrown resolving a single-frame image stream:
XMLHttpRequest error.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 977:28                get current
packages/http/src/browser_client.dart 69:22                                       <fn>
dart-sdk/lib/async/zone.dart 1660:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 558:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1587:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37367:58                              <fn>
Image provider: FMNetworkImageProvider()
Image key: FMNetworkImageProvider()
====================================================================================================
```

**Comment by JaffaKetchup** [comment]
Running the example application on the web yields a 418 I'm a Teapot response:

![image](https://user-images.githubusercontent.com/58115698/232227773-1f750efe-61c2-4f24-9a38-d2c58e540bc2.png)
![image](https://user-images.githubusercontent.com/58115698/232227941-43ba1de8-7d3e-4c39-918c-3cbc8daad8e2.png)

I can open tiles manually on the web with a referrer of openstreetmap.org:

![image](https://user-images.githubusercontent.com/58115698/232227987-7fdf0ccd-f111-4e7a-867c-dc16acfd8c41.png)

This appears to be the fault of OSM, but it may also be Flutter changing something in the 3.7 update(s)?

**Comment by JaffaKetchup** [comment]
It is important to note that unfortunately, we do not have control over the User-Agent on web, due to Dart limitations. I suspect this is the issue: https://help.openstreetmap.org/questions/83828/tile-layer-418-error.
We may have to wait a while.

**Comment by JaffaKetchup** [comment]
Fixed by the OSM team.

**Comment by GULERTOLGA** [comment]
I could not fully understand whether I can use osm servers on the web. I'm still getting the CORS error. Is there a solution?

**Comment by JaffaKetchup** [comment]
Hi @GULERTOLGA,
This problem was resolved externally by the OSM team and was caused by a 'standards non-conforming' browser update.
Please include your Flutter version, your browser & version, and any other useful information.

**Comment by GULERTOLGA** [comment]
hi @JaffaKetchup 
```
   TileLayer(
              minZoom: 6,
              maxZoom: 19,
              urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
              subdomains: const ['a', 'b', 'c'],
              tileProvider: NetworkNoRetryTileProvider(
                headers: {
                  "Access-Control-Allow-Origin": "*",
                },
              ),
            ),
```


**error is**

Access to XMLHttpRequest at 'https://a.tile.openstreetmap.org/14/9680/6208.png' from origin 'https://myserver.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.


**chrome version**

Chrome is up to date
Version 114.0.5735.90 (Official Build) (arm64)



**Flutter doctor result**

tolgamini@Tolgas-Mac-mini nfield % fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0 22A380 darwin-arm64 (Rosetta), locale en-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
tolgamini@Tolgas-Mac-mini nfield % fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0 22A380 darwin-arm64 (Rosetta), locale en-TR)
    • Flutter version 3.10.2 on channel stable at /Users/tolgamini/fvm/versions/3.10.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (9 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/tolgamini/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.74.2)
    • VS Code at /Volumes/Seagate/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Redmi Note 9S (mobile) • 73a631d6 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 13.0 22A380 darwin-arm64 (Rosetta)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.


thank you for your attention

**Comment by GULERTOLGA** [comment]
I deployed the same web application to two different domains. The same code works fine in one of the domains, and I keep getting a cors error in the other. Do you have a comment on this? thanks

**Comment by JaffaKetchup** [comment]
It's possible you've been blocked. If not, make sure you've set a `userAgentPackageName`. Other than that, there's not much we can do.
