### ISSUE TITLE
Unbounded scroll/marker jump: Markers disappear

### ISSUE THREAD

**Issue by S-Man42** [fleaflet/flutter_map#2038]
### What is the bug?

![Image](https://github.com/user-attachments/assets/13c8842a-9d7a-469c-b0e9-8d013bb50400)
(Better quality: https://s-man42.de/flutterMapMarkers.gif)

I tried to add two markers to my map (which I connected by a polyline which crosses the date border). Zoomed out (low zoom level), when scrolling I find a moment in which all markers disappeared - but they re-appear some moments later.

Zooming in, I can reproduce that all markers completely disappear whereas my polyline is still visible.

![Image](https://github.com/user-attachments/assets/4aca1467-9376-4246-84af-02fd9039aecb)

I am not sure if it is a bug or I miss some settings...

### How can we reproduce it?

I hope it is just an issue on my side e.g some settings, otherwise I will try to extract the essence out of my map code furtherly.

I am using the flutter_map_marker_popup from this current merge request: https://github.com/rorystephenson/flutter_map_marker_popup/pull/86

**Comment by monsieurtanuki** [comment]
It's probably fixed with the latest github code (which is ahead of the latest official version).

**Comment by enricostrijks** [comment]
Once #2046 is released I will update the flutter_map package in my repo to that version @S-Man42 in the meantime we just have to wait for that to be merged and released.

**Comment by JaffaKetchup** [comment]
@enricostrijks @S-Man42 Does the issue still occur with the latest code on v8.1? #2046 looks like it might be unrelated?

**Comment by S-Man42** [comment]
I'll check asap

**Comment by JaffaKetchup** [comment]
For the time being, I'm going to assume this is resolved. If not, please feel free to ping me and I'll re-open!

**Comment by S-Man42** [comment]
Sorry, unfortunately I didn't had the time to check far due to personal issues. But I did not forget it. I will do next week I hope.

**Comment by scapin01** [comment]
Hello, with the version 8.1.1 it is still reproducible.
Steps:
 -> Clone https://github.com/enricostrijks/flutter_map_marker_popup.git
-> Upgrade flutter_map to 8.1.1 (i's currently 8.0.0).
-> Start the example application.

The Markers are only visible at certain zoom levels:

**Comment by JaffaKetchup** [comment]
Does the issue occur with native `Marker`s?

**Comment by scapin01** [comment]
> Does the issue occur with native `Marker`s?

Not it does not occur with the native markers. After further investigation, I found out that 'MarkerLayer' was not adapted in the `flutter_marker_popup` package to the newly added multi world feature. So it seems it's not an issue with `flutter_map` directly.

**Comment by Mike-3** [comment]
In version 8.1.1  flutter_map crashes after creating points.

![Image](https://github.com/user-attachments/assets/7e97243c-ead6-432a-9fe3-47e9fa93f4f6)
